all: false
recursive: true
packages:
#  testproj/internal/testpckg:
#    # place your package-specific config here
#    config:
#      dir: "{{.InterfaceDir}}/mocks"
#      outpkg: mocks
#    interfaces:
#      TestInterface:
